image: php:8.3-apache

# variables:
#   PHP_MEMORY_LIMIT: 2G
#   APP_ENV: test

services:
  - name: mysql:5.7
    alias: db

cache:
  paths:
    - vendor/
    - ~/.composer/cache

before_script:
  - apt-get update && apt-get install -y git unzip libzip-dev zlib1g-dev default-mysql-client
  - docker-php-ext-install pdo pdo_mysql
  - curl -sS https://getcomposer.org/installer | php
  - mv composer.phar /usr/local/bin/composer
  - composer install
  # - php bin/console doctrine:database:create --if-not-exists --env=test
  # - php bin/console doctrine:schema:update --force --env=test

stages:
  - build
  - test

build:
  stage: build
  script:
    - composer install
  artifacts:
    paths:
      - vendor/
phpunit:
  stage: test
  script:
    - php bin/phpunit --configuration phpunit.xml.dist
  allow_failure: false
  
